:author1: Angelika Weiß
:email1:  weiss.ang@web.de
:keywords: kammmolch, triturus cristatus
:icons:     font
:toc:  left
:toclevels: 4
:toc-title: Inhaltsverzeichnis
:imagesdir: ./images
:doctype: book
:pdf-theme: techinfo-theme.yml
:stem: 
:title-separator: {sp}|

Kammmolch-Projekt

Zwischenbericht 2021
 
Stützung des Kammmolchvorkommens auf der DBU-Naturerbefläche Frauenholz bei Oberhinkofen Landkreis Regensburg, Bayern
 
Autoren:
Hartmut Schmid,  Franz Häring, Angelika Weiß, Marianne Häring, Tom Aumer
 
 
 
 
 
 
 
 
 



 
 
Impressum:
Hartmut Schmidt                                      
Landschaftspflegeverband Regensburg e.V. 
Altmühlstraße 3
93059 Regensburg
www.lpv-regensburg.de

== Einführung

Der Kammmolch (Triturus cristatus) ist eine gefährdete und in Deutschland streng geschützte Art (Rote Liste: 2 – stark gefährdet / FFH-RL Anhänge II und IV). 

allg. Infos zu Kammmolch

- letztes bekanntes Vorkommen in Stadt und Lkr. Regensburg
- FFH-Managementplan für DBU-Naturerbefläche als Grundlage für Populationsstützungsmaßnahmen
- Fortsetzung des Artenhilfsprojekts der Regierung der Oberpfalz mit Maßnahmen zur Verbesserung des Kammmolch-Laichgewässers in der DBU-Naturerbefläche vom März 2021 durch H. Schmid/LPV

=== Projektbeteiligte

Das Projekt wurde durch die Regierung der Oberpfalz initiiert und durch den Gebietsbetreuer Hartmut Schmid durchgeführt. Beteiligt sind außerdem die ehrenamtlichen Mitarbeiter*innen Tom Aumer, Franz und Marianne Häring sowie Angelika Weiß. 

=== Projektziele

- Bestandserfassung qualitativ und quantitativ über mehrere Jahre, beginnend 2021, da nach dem letzten Monitoring im Jahre ?? unklar war, wie viele Exemplare überhaupt noch im Gewässer vorhanden sind
- Bestandsstützung und -vergrößerung durch Aufzucht von Nachkommen in Aquarien und Wiederaussetzung [in Abhängigkeit von Fangzahlen, ggf. an weiteren geeigneten Gewässern in der Umgebung]

== Methodik

=== Bestandserfassung

====  Fang adulter Tiere

Am 29.4.21 wurden abends ab 18 h insgesamt 11 Molchreusen an verschiedenen Stellen im Hauptgewässer eingebracht (Abb. 2.1.1 a,  Abb. 2.1.1 b).  Dabei wurde leider deutlich, dass aufgrund der geringen Niederschläge die Wassertiefe z.T. unter 30 cm gefallen war, da einzelne der Schwimmreusen auf dem Gewässergrund auflagen. Die eingebrachten PET-Flaschen als Schwimmkörper waren dort gar nicht erforderlich. 
Abb. 2.1.1 a: Einbringen der Molchreusen ins Gewässer

Abb. 2.1.1 b: Alle am 29.4.21 eingebrachten Molchreusen
Am 30.4.21 wurden ab 10 Uhr die Reusen kontrolliert und in 8 der 11 Reusen Teich-, Berg- und/oder Kammmolche gefunden. Die Tiere wurden vorsichtige in eine größere Wanne mit Frischwasser gegeben, um die jeweiligen Gesamtzahlen sowie die Geschlechter feststellen zu können. Die Kammmolche wurden einzeln in einer Fotoküvette fotografiert (siehe 2.1.2) um im Projektverlauf Informationen für die Abschätzung der Populationsgröße zu erhalten. Außerdem wurde damit beurteilt, wie viele trächtige Weibchen sich unter den gefangenen Individuen befanden, welche ggf. zum Ablaichen in das Aquarium überführt werden sollten. 
2.1.2 Monitoring
Die erwachsenen Kammmolche wurden vorsichtig in eine 5 cm x 5 cm x 20 cm große Plexiglas-Fotoküvette gegeben und diese in ein selbstgebautes Stativ (siehe Abb. 2.1.2 a) eingeklemmt. Sobald die Molche nach oben schwammen, wurden ihre Bauchseiten fotografiert, um sie vermessen und erstmalig sowie bei einem Wiederfang identifizieren zu können. Danach wurden sie vorsichtig in den späteren Transportbehälter mit Teichwasser  gegeben bis zur Entscheidung, welche/s der Tiere zum Ablaichen ins Aquarium gebracht werden sollte. Die Jungtiere wurden in einer 10 cm x 10 cm x 3 cm (lichte Weite) große Fotoküvette gegeben, da hiermit die Fotodokumentation, insbesondere auch die Längenmessung einfacher war (siehe Abb. 2.1.2b) 











Abb. 2.1.2.a				Abb. 2.1.2.b

2.2 Gewinnung von Laich für die Nachzuchten
2.2.1. Haltung trächtiger Tiere in den Aquarien
Die wie oben (2.1.1.) beschrieben gefangenen Tiere wurden in dem Transportbehälter mit Moos schnellstmöglich zum vorbereiteten Aquarium transportiert und dort bis zum …. gehältert. Das 300l-Aquarium war bereits im Vorfeld [wieviele Tage?] mit Pflanzen der Gattung Ammannia praetermissa, […] bestückt (siehe Abb. 2.2.1 a). Das Wasser hatte eine Temperatur von 16°C, pH von 7,2, Wasserhärte 9 °dH,Cl-, NO2- und NO3- bei 0. 


Abb. 2.2.1 a Foto Aquarium (wenn vorhanden)
Nach Einsetzen der Kammmolche wurden diese x mal täglich mit selbst gezogenen Daphnien [Daphnia ?] und Stechmückenlarven [Culex pipiens] gefüttert.
[→ Ablauf so richtig dargestellt? Fütterung? Fotos Aquarium→ Infos von Tom nötig]
Aus Vorsichtsgründen wurden am 4.5.2021 ein Teil der abgelegten Kammmolch-Eier an/mit den Ammania-Pflanzen (siehe 3.1 Ergebnisse) in das Aquarium übertragen, in welchem sich keine Adulten befanden und das Adultenaquarium neu mit Pflanzen bestückt.  
2.2.2. Entnahme von Eiern aus dem Gewässer 
Analog der Vorgehensweise von Kaltenbacher wurden am 1.4.2021 insgesamt 11 Pflanzkörbe bzw. Pflanzgefäße mit Lysimachia numularia, welches im Umgriff des Kammmolch-Laichgewässers gefunden wurde, bestückt und auf den Gewässergrund verbracht (Abb. 2.2.2 a – 2.2.2 c), um den Kammmolchen die für die Eiablage benötigten Wasserpflanzen anzubieten. 
Abb. 2.2.2a					Abb. 2.2.2 b

Abb. 2.2.2 c

Die 11 Pflanzkörbe bzw. Pflanzgefäße wurden am 30.4.2021 entnommen und kontrolliert, wie viele der typischen zusammengefalteten Blätter – welche ein darin hineingeklebtes Ei vermuten ließen – an den Pflanzen erkennbar waren.  Es wurden zwei der Lysimachia-Pflanzkörbe bzw. Pflanzgefäße entnommen, an welchen insgesamt 15 Blätter zusammengeklebt waren, damit Eier vermuten ließen. 
Die Gefäße wurden in eine große Wanne mit Teichwasser gegeben, so dass die Pflanzen einschließlich der eingefalteten Eier mit Wasser bedeckt blieben (siehe Abb. 2.2.2 d). In dieser Wanne wurden sie zu einem zweiten Aquarium transportiert und in dieses eingebracht.












Abb. 2.2.2 d
→ Aquariumgröße? Wassertemperatur, - zusammensetzung – analog Adultenaquarium? Fütterung der Larven? Fotos Aquarium ?→ Infos von Tom nötig, Dokumentation des Schlupfs möglich?

3. Ergebnisse
3.1 Populationsgröße Ausgangsbestand Kammmolche 
Tabelle mit Fangdaten männlich/weiblich/juvenil zum jeweiligen Fangzeitpunkt
Fotos der einzelnen Individuen → BioMap
Gewässerfauna
Im Untersuchungsgewässer wurden in den Reusen am 30.4.2021 neben den 8 Kammmolchen (je 3 adulte Weibchen und Männchen und zwei Jungtiere) noch zwei Bergmolche (Ichtyosaurus alpestris, je ein Weibchen und ein Männchen) sowie 15 Teichmolche (Lissotriton vulgaris, 10 Männchen und 5 Weibchen) gefunden sowie ein Grünfrosch, eine Erdkröte, mehrere Rückenschwimmer und zwei Gelbrandkäfer. Im Wasser konnte eine Gelbbauchunke beobachtet werden. Aufgrund des sehr trüben Wassers war eine Bewertung, ob sich noch andere Tiere, insbesondere auch Prädatoren darin befanden, nicht möglich. 
3.2 Nachzucht
3.2.1 Vermehrung durch Eiablage Adulti
Das am 30.4.2021 entnommene trächtige Weibchen #2 begann am … mit der Eiablage und hatte bis zum 4.5.2021 insgesamt 15 Eier an Wasserpflanzen ausschließlich der Gattung  Ammannia praetermissa abgelegt (siehe Abb. 3.2.1)
3.2.2 Vermehrung durch Eier an Pflanzen
4. Schlussfolgerungen

 

Literaturverzeichnis
Kaltenbacher, Kathrin (Dez. 2020): Artenhilfsmaßnahme Kammmolch – Nachzuchtprogramm und Wiederansiedlung der gefährdeten Amphibienart Kammmolch (Triturus cristatus) in ausgewählten Lebensräumen im Landkreis Landshut. 
 
 
